'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Xtravo.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _173_3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_173_3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _191_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_191_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property addfav() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addfav", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Xtravo.
        '''</summary>
        Friend ReadOnly Property AppName() As String
            Get
                Return ResourceManager.GetString("AppName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''
        '''&lt;head&gt;
        '''&lt;title&gt;This site had been blocked.&lt;/title&gt;
        '''&lt;meta name=&quot;generator&quot; content=&quot;Namo WebEditor v5.0&quot;&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body bgcolor=&quot;white&quot; text=&quot;black&quot; link=&quot;blue&quot; vlink=&quot;purple&quot; alink=&quot;red&quot;&gt;
        '''&lt;p align=&quot;center&quot;&gt;&lt;font size=&quot;6&quot;&gt;&lt;em&gt;&lt;font color=&quot;#990000&quot; face=&quot;Tahoma&quot;&gt;&lt;font color=&quot;#333333&quot; face=&quot;Calibri&quot;&gt;This Site has been Blocked by You. &lt;/font&gt;&lt;/font&gt;&lt;/em&gt;&lt;/font&gt;&lt;/p&gt;
        '''&lt;p align=&quot;center&quot;&gt;&lt;img src=&quot;http://www.jawoco.com/images/jawoco.jpg&quot; width=&quot;563&quot; height=&quot;85&quot;&gt;&lt;/p&gt;
        '''&lt;p align=&quot;center&quot;&gt;&lt;font face=&quot;Ca [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Blocked() As String
            Get
                Return ResourceManager.GetString("Blocked", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Delete16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Globe() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Globe", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LockOpen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockOpen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NoPopUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NoPopUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property popallowed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("popallowed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property popBlocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("popBlocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Star2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''&lt;head&gt;
        '''&lt;title&gt;Example Browser - Start Page&lt;/title&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body bgcolor=&quot;white&quot; text=&quot;black&quot; link=&quot;blue&quot; vlink=&quot;purple&quot; alink=&quot;red&quot;&gt;
        '''&lt;p align=&quot;center&quot;&gt;&lt;font face=&quot;Tahoma&quot; size=&quot;4&quot;&gt;&lt;b&gt;Working with the WebBrowser Control 
        '''in Visual Studio 2005.&lt;br&gt;&lt;/b&gt;&lt;/font&gt;&lt;/p&gt;
        '''&lt;p align=&quot;center&quot;&gt;&lt;font face=&quot;Tahoma&quot; size=&quot;2&quot;&gt;&lt;b&gt;1st&lt;/b&gt;&lt;/font&gt;&lt;font face=&quot;Tahoma&quot;&gt;&lt;b&gt;: &lt;/b&gt;&lt;/font&gt;&lt;font face=&quot;Tahoma&quot; size=&quot;2&quot;&gt;&lt;b&gt;Please 
        '''vote for this example on the site you found it on if you find it useful.&lt;/b&gt;&lt;/font&gt;&lt;/p&gt;
        '''&lt;p  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property StartPage() As String
            Get
                Return ResourceManager.GetString("StartPage", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Windows_Pop_up_Blocked() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Pop_up_Blocked", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
